# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

In [2]:
import pandas as pd

url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv'

df = pd.read_csv(url)
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   Customer                       10910 non-null  str
 2   State                          10279 non-null  str
 3   Customer Lifetime Value        10910 non-null  float64
 4   Response                       10279 non-null  str
 5   Coverage                       10910 non-null  str
 6   Education                      10910 non-null  str
 7   Effective To Date              10910 non-null  str
 8   EmploymentStatus               10910 non-null  str
 9   Gender                         10910 non-null  str
 10  Income                         10910 non-null  int64
 11  Location Code                  10910 non-null  str
 12  Marital Status                 10910 non-null  str
 13  Monthly Premium Auto           10910 non-null  int64
 14  Months Since Last Claim        10277 non-null  float64
 15  Months Since Policy Inception  10910 non-null  int64
 16  Number of Open Complaints      10277 non-null  float64
 17  Number of Policies             10910 non-null  int64
 18  Policy Type                    10910 non-null  str
 19  Policy                         10910 non-null  str
 20  Renew Offer Type               10910 non-null  str
 21  Sales Channel                  10910 non-null  str
 22  Total Claim Amount             10910 non-null  float64
 23  Vehicle Class                  10288 non-null  str
 24  Vehicle Size                   10288 non-null  str
 25  Vehicle Type                   5428 non-null   str
dtypes: float64(4), int64(5), str(17)
memory usage: 2.2 MB

In [4]:
df.shape

(10910, 26)

In [5]:
df.nunique()

Unnamed: 0                       10910
Customer                          9134
State                                5
Customer Lifetime Value           8041
Response                             2
Coverage                             3
Education                            5
Effective To Date                   59
EmploymentStatus                     5
Gender                               2
Income                            5694
Location Code                        3
Marital Status                       3
Monthly Premium Auto               202
Months Since Last Claim             36
Months Since Policy Inception      100
Number of Open Complaints            6
Number of Policies                   9
Policy Type                          3
Policy                               9
Renew Offer Type                     4
Sales Channel                        4
Total Claim Amount                5106
Vehicle Class                        6
Vehicle Size                         3
Vehicle Type                         1
dtype: int64

**Cleaning**

In [6]:
def clear_data (dataf: pd.Series) -> pd.Series:
    dataf = dataf.str.upper().str.strip()
    return dataf

In [7]:
df.columns = [(column.lower()).replace(" ","_") for column in df.columns]
df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [8]:
df.isna().sum()

unnamed:_0                          0
customer                            0
state                             631
customer_lifetime_value             0
response                          631
coverage                            0
education                           0
effective_to_date                   0
employmentstatus                    0
gender                              0
income                              0
location_code                       0
marital_status                      0
monthly_premium_auto                0
months_since_last_claim           633
months_since_policy_inception       0
number_of_open_complaints         633
number_of_policies                  0
policy_type                         0
policy                              0
renew_offer_type                    0
sales_channel                       0
total_claim_amount                  0
vehicle_class                     622
vehicle_size                      622
vehicle_type                     5482
dtype: int64

In [9]:
df.marital_status.value_counts()

marital_status
Married     6319
Single      2958
Divorced    1633
Name: count, dtype: int64

In [10]:
df.number_of_open_complaints = df.number_of_open_complaints.fillna(0).map(int)
df

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,0,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,1/19/11,Unemployed,F,...,0,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,1/6/11,Employed,F,...,0,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2/6/11,Employed,F,...,0,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,NaN
10908,10908,WA60547,California,11971.977650,No,Premium,College,2/13/11,Employed,F,...,4,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A
10909,10909,IV32877,NaN,6857.519928,NaN,Basic,Bachelor,1/8/11,Unemployed,M,...,0,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,NaN

In [11]:
df.customer_lifetime_value = df.customer_lifetime_value.round(2)

In [12]:
df.total_claim_amount = df.total_claim_amount.round(2)
df

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,0,DK49336,Arizona,4809.22,No,Basic,College,2/18/11,Employed,M,...,0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.80,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.53,No,Basic,College,1/18/11,Unemployed,F,...,0,1,Personal Auto,Personal L3,Offer4,Call Center,744.92,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.92,No,Basic,Bachelor,2/10/11,Employed,M,...,0,2,Personal Auto,Personal L3,Offer3,Call Center,480.00,SUV,Medsize,A
3,3,XL78013,Oregon,22332.44,Yes,Extended,College,1/11/11,Employed,M,...,0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.01,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.07,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,0,7,Personal Auto,Personal L2,Offer1,Branch,707.93,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.37,No,Premium,Bachelor,1/19/11,Unemployed,F,...,0,7,Personal Auto,Personal L1,Offer3,Web,1214.40,Luxury Car,Medsize,A
10906,10906,KX53892,Oregon,5259.44,No,Basic,College,1/6/11,Employed,F,...,0,6,Personal Auto,Personal L3,Offer2,Branch,273.02,Four-Door Car,Medsize,A
10907,10907,TL39050,Arizona,23893.30,No,Extended,Bachelor,2/6/11,Employed,F,...,0,2,Corporate Auto,Corporate L3,Offer1,Web,381.31,Luxury SUV,Medsize,NaN
10908,10908,WA60547,California,11971.98,No,Premium,College,2/13/11,Employed,F,...,4,6,Personal Auto,Personal L1,Offer1,Branch,618.29,SUV,Medsize,A
10909,10909,IV32877,NaN,6857.52,NaN,Basic,Bachelor,1/8/11,Unemployed,M,...,0,3,Personal Auto,Personal L1,Offer4,Web,1021.72,SUV,Medsize,NaN

In [13]:
df = df.drop(['unnamed:_0'], axis=1)
df

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,DK49336,Arizona,4809.22,No,Basic,College,2/18/11,Employed,M,48029,...,0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.80,Four-Door Car,Medsize,NaN
1,KX64629,California,2228.53,No,Basic,College,1/18/11,Unemployed,F,0,...,0,1,Personal Auto,Personal L3,Offer4,Call Center,744.92,Four-Door Car,Medsize,NaN
2,LZ68649,Washington,14947.92,No,Basic,Bachelor,2/10/11,Employed,M,22139,...,0,2,Personal Auto,Personal L3,Offer3,Call Center,480.00,SUV,Medsize,A
3,XL78013,Oregon,22332.44,Yes,Extended,College,1/11/11,Employed,M,49078,...,0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.01,Four-Door Car,Medsize,A
4,QA50777,Oregon,9025.07,No,Premium,Bachelor,1/17/11,Medical Leave,F,23675,...,0,7,Personal Auto,Personal L2,Offer1,Branch,707.93,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,FE99816,Nevada,15563.37,No,Premium,Bachelor,1/19/11,Unemployed,F,0,...,0,7,Personal Auto,Personal L1,Offer3,Web,1214.40,Luxury Car,Medsize,A
10906,KX53892,Oregon,5259.44,No,Basic,College,1/6/11,Employed,F,61146,...,0,6,Personal Auto,Personal L3,Offer2,Branch,273.02,Four-Door Car,Medsize,A
10907,TL39050,Arizona,23893.30,No,Extended,Bachelor,2/6/11,Employed,F,39837,...,0,2,Corporate Auto,Corporate L3,Offer1,Web,381.31,Luxury SUV,Medsize,NaN
10908,WA60547,California,11971.98,No,Premium,College,2/13/11,Employed,F,64195,...,4,6,Personal Auto,Personal L1,Offer1,Branch,618.29,SUV,Medsize,A
10909,IV32877,NaN,6857.52,NaN,Basic,Bachelor,1/8/11,Unemployed,M,0,...,0,3,Personal Auto,Personal L1,Offer4,Web,1021.72,SUV,Medsize,NaN

In [14]:
df.response = clear_data(df.response)
df

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,DK49336,Arizona,4809.22,NO,Basic,College,2/18/11,Employed,M,48029,...,0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.80,Four-Door Car,Medsize,NaN
1,KX64629,California,2228.53,NO,Basic,College,1/18/11,Unemployed,F,0,...,0,1,Personal Auto,Personal L3,Offer4,Call Center,744.92,Four-Door Car,Medsize,NaN
2,LZ68649,Washington,14947.92,NO,Basic,Bachelor,2/10/11,Employed,M,22139,...,0,2,Personal Auto,Personal L3,Offer3,Call Center,480.00,SUV,Medsize,A
3,XL78013,Oregon,22332.44,YES,Extended,College,1/11/11,Employed,M,49078,...,0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.01,Four-Door Car,Medsize,A
4,QA50777,Oregon,9025.07,NO,Premium,Bachelor,1/17/11,Medical Leave,F,23675,...,0,7,Personal Auto,Personal L2,Offer1,Branch,707.93,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,FE99816,Nevada,15563.37,NO,Premium,Bachelor,1/19/11,Unemployed,F,0,...,0,7,Personal Auto,Personal L1,Offer3,Web,1214.40,Luxury Car,Medsize,A
10906,KX53892,Oregon,5259.44,NO,Basic,College,1/6/11,Employed,F,61146,...,0,6,Personal Auto,Personal L3,Offer2,Branch,273.02,Four-Door Car,Medsize,A
10907,TL39050,Arizona,23893.30,NO,Extended,Bachelor,2/6/11,Employed,F,39837,...,0,2,Corporate Auto,Corporate L3,Offer1,Web,381.31,Luxury SUV,Medsize,NaN
10908,WA60547,California,11971.98,NO,Premium,College,2/13/11,Employed,F,64195,...,4,6,Personal Auto,Personal L1,Offer1,Branch,618.29,SUV,Medsize,A
10909,IV32877,NaN,6857.52,NaN,Basic,Bachelor,1/8/11,Unemployed,M,0,...,0,3,Personal Auto,Personal L1,Offer4,Web,1021.72,SUV,Medsize,NaN

In [15]:
df.shape

(10910, 25)

1. Create a new DataFrame that only includes customers who:
    - have a **low total_claim_amount** (e.g., below $1,000)
    - have a response \"Yes\" to the last marketing campaign.

In [16]:
low_t_c_amount = df[ df.total_claim_amount < 1000 ]
low_t_c_amount

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
0,DK49336,Arizona,4809.22,NO,Basic,College,2/18/11,Employed,M,48029,...,0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.80,Four-Door Car,Medsize,NaN
1,KX64629,California,2228.53,NO,Basic,College,1/18/11,Unemployed,F,0,...,0,1,Personal Auto,Personal L3,Offer4,Call Center,744.92,Four-Door Car,Medsize,NaN
2,LZ68649,Washington,14947.92,NO,Basic,Bachelor,2/10/11,Employed,M,22139,...,0,2,Personal Auto,Personal L3,Offer3,Call Center,480.00,SUV,Medsize,A
3,XL78013,Oregon,22332.44,YES,Extended,College,1/11/11,Employed,M,49078,...,0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.01,Four-Door Car,Medsize,A
4,QA50777,Oregon,9025.07,NO,Premium,Bachelor,1/17/11,Medical Leave,F,23675,...,0,7,Personal Auto,Personal L2,Offer1,Branch,707.93,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10903,SU71163,Arizona,2771.66,NO,Basic,College,1/7/11,Employed,M,59855,...,4,1,Personal Auto,Personal L2,Offer2,Branch,355.20,Two-Door Car,Medsize,A
10904,QI63521,Nevada,19228.46,NO,Basic,High School or Below,2/24/11,Unemployed,M,0,...,0,2,Personal Auto,Personal L2,Offer1,Branch,897.60,Luxury SUV,Medsize,A
10906,KX53892,Oregon,5259.44,NO,Basic,College,1/6/11,Employed,F,61146,...,0,6,Personal Auto,Personal L3,Offer2,Branch,273.02,Four-Door Car,Medsize,A
10907,TL39050,Arizona,23893.30,NO,Extended,Bachelor,2/6/11,Employed,F,39837,...,0,2,Corporate Auto,Corporate L3,Offer1,Web,381.31,Luxury SUV,Medsize,NaN
10908,WA60547,California,11971.98,NO,Premium,College,2/13/11,Employed,F,64195,...,4,6,Personal Auto,Personal L1,Offer1,Branch,618.29,SUV,Medsize,A

In [17]:
response_yes = df[df.response == 'YES' ]
response_yes

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,XL78013,Oregon,22332.44,YES,Extended,College,1/11/11,Employed,M,49078,...,0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.01,Four-Door Car,Medsize,A
8,FM55990,California,5989.77,YES,Premium,College,1/19/11,Employed,M,66839,...,0,1,Personal Auto,Personal L1,Offer2,Branch,739.20,Sports Car,Medsize,NaN
15,CW49887,California,4626.80,YES,Basic,Master,1/16/11,Employed,F,79487,...,0,1,Special Auto,Special L1,Offer2,Branch,547.20,SUV,Medsize,NaN
19,NJ54277,California,3746.75,YES,Extended,College,2/26/11,Employed,F,41479,...,1,1,Personal Auto,Personal L2,Offer2,Call Center,19.58,Two-Door Car,Large,A
27,MQ68407,Oregon,4376.36,YES,Premium,Bachelor,2/28/11,Employed,F,63774,...,0,1,Personal Auto,Personal L3,Offer2,Agent,60.04,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,FM31768,Arizona,5979.72,YES,Extended,High School or Below,2/7/11,Employed,F,57693,...,0,3,Personal Auto,Personal L1,Offer2,Agent,547.20,Four-Door Car,Medsize,NaN
10852,KZ80424,Washington,8382.48,YES,Basic,Bachelor,1/27/11,Employed,M,25998,...,0,2,Personal Auto,Personal L2,Offer2,Call Center,791.88,NaN,NaN,A
10872,XT67997,California,5979.72,YES,Extended,High School or Below,2/7/11,Employed,F,57693,...,0,3,Personal Auto,Personal L3,Offer2,Agent,547.20,Four-Door Car,Medsize,NaN
10887,BY78730,Oregon,8879.79,YES,Basic,High School or Below,2/3/11,Employed,F,52583,...,0,7,Special Auto,Special L2,Offer1,Agent,528.20,SUV,Small,A
10897,MM70762,Arizona,9075.77,YES,Basic,Master,1/26/11,Employed,M,37722,...,0,8,Personal Auto,Personal L1,Offer1,Agent,158.08,Sports Car,Medsize,A

In [18]:
filtered_df = df[(df.response == 'YES') & (df.total_claim_amount < 1000)]
filtered_df

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,XL78013,Oregon,22332.44,YES,Extended,College,1/11/11,Employed,M,49078,...,0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.01,Four-Door Car,Medsize,A
8,FM55990,California,5989.77,YES,Premium,College,1/19/11,Employed,M,66839,...,0,1,Personal Auto,Personal L1,Offer2,Branch,739.20,Sports Car,Medsize,NaN
15,CW49887,California,4626.80,YES,Basic,Master,1/16/11,Employed,F,79487,...,0,1,Special Auto,Special L1,Offer2,Branch,547.20,SUV,Medsize,NaN
19,NJ54277,California,3746.75,YES,Extended,College,2/26/11,Employed,F,41479,...,1,1,Personal Auto,Personal L2,Offer2,Call Center,19.58,Two-Door Car,Large,A
27,MQ68407,Oregon,4376.36,YES,Premium,Bachelor,2/28/11,Employed,F,63774,...,0,1,Personal Auto,Personal L3,Offer2,Agent,60.04,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,FM31768,Arizona,5979.72,YES,Extended,High School or Below,2/7/11,Employed,F,57693,...,0,3,Personal Auto,Personal L1,Offer2,Agent,547.20,Four-Door Car,Medsize,NaN
10852,KZ80424,Washington,8382.48,YES,Basic,Bachelor,1/27/11,Employed,M,25998,...,0,2,Personal Auto,Personal L2,Offer2,Call Center,791.88,NaN,NaN,A
10872,XT67997,California,5979.72,YES,Extended,High School or Below,2/7/11,Employed,F,57693,...,0,3,Personal Auto,Personal L3,Offer2,Agent,547.20,Four-Door Car,Medsize,NaN
10887,BY78730,Oregon,8879.79,YES,Basic,High School or Below,2/3/11,Employed,F,52583,...,0,7,Special Auto,Special L2,Offer1,Agent,528.20,SUV,Small,A
10897,MM70762,Arizona,9075.77,YES,Basic,Master,1/26/11,Employed,M,37722,...,0,8,Personal Auto,Personal L1,Offer1,Agent,158.08,Sports Car,Medsize,A

In [19]:
df.shape

(10910, 25)

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

I want to check results with non-filter dataframe (df) and  with filtered dataframe (response_yes)

In [20]:
df_pivot1 = df.pivot_table(index='policy_type', columns='gender', values='monthly_premium_auto', aggfunc='mean')
df_pivot1

gender                  F          M
policy_type
Corporate Auto  91.384615  94.764249
Personal Auto   93.153179  93.301056
Special Auto    93.563025  93.197044

In [21]:
df_pivot = response_yes.pivot_table(index='policy_type', columns='gender', values='monthly_premium_auto', aggfunc='mean')
df_pivot

gender                  F          M
policy_type
Corporate Auto  94.301775  92.188312
Personal Auto   98.998148  91.085821
Special Auto    92.314286  86.343750

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [22]:
# I wanted to check how to use pivot_table for grouping
res = df.pivot_table(index='state', values='customer', aggfunc='count') 
res

            customer
state
Arizona         1937
California      3552
Nevada           993
Oregon          2909
Washington       888

In [23]:
result1 = df.groupby('state')['customer'].size()
result1

state
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: customer, dtype: int64

In [24]:
result = df.groupby('state')['customer'].count()
result

state
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: customer, dtype: int64

In [25]:
r = df.groupby('state')['customer'].size()
res = r[r > 500]
res

state
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: customer, dtype: int64

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [26]:
grouped_df = df.groupby('education')['customer_lifetime_value'].agg(['max', 'min', 'median'])
grouped_df

                           max      min   median
education
Bachelor              73225.96  1898.01  5579.38
College               61850.19  1898.68  5813.63
Doctor                44856.11  2267.60  5423.14
High School or Below  83325.38  1940.98  6189.35
Master                51016.07  2272.31  5680.47

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [41]:
df['months_since_last_claim'] = df['months_since_last_claim'].fillna(0).map(int)

In [54]:
df.effective_to_date.unique()

<StringArray>
['2/18/11', '1/18/11', '2/10/11', '1/11/11', '1/17/11', '2/14/11', '2/24/11',
 '1/19/11',  '1/4/11',  '1/2/11',  '2/7/11', '1/31/11', '1/26/11', '2/28/11',
 '1/16/11', '2/26/11', '2/23/11', '1/15/11',  '2/2/11', '2/15/11', '1/24/11',
 '2/21/11', '2/22/11',  '1/7/11', '1/28/11',  '2/8/11', '2/12/11', '2/20/11',
  '1/5/11', '2/19/11',  '1/3/11',  '2/3/11', '1/22/11', '1/23/11',  '2/5/11',
 '2/13/11', '1/25/11', '2/16/11',  '2/1/11', '1/27/11', '1/12/11', '1/20/11',
  '2/6/11', '2/11/11', '1/21/11', '1/29/11',  '1/9/11',  '2/9/11', '2/27/11',
  '1/1/11', '2/17/11', '2/25/11', '1/13/11',  '1/6/11',  '2/4/11', '1/14/11',
 '1/10/11',  '1/8/11', '1/30/11']
Length: 59, dtype: str

In [75]:
copy_df = df.copy()
# copy_df['effective_to_date'] = copy_df['effective_to_date'].str[0] - we can't guarantee that we get a month
# month = pd.to_datetime(df['effective_to_date']).dt.month - effective way but to add new column is more useful for future

copy_df['month'] = pd.to_datetime(copy_df['effective_to_date']).dt.month
copy_df
df = copy_df

/var/folders/1q/2t5621cd5kz7blvfr_nw9dl80000gn/T/ipykernel_1625/3836194334.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  copy_df['month'] = pd.to_datetime(copy_df['effective_to_date']).dt.month

In [72]:
#policies_by_month1 = df.groupby('state')['policy'].agg(['count'])

In [86]:
policies_by_month = df.pivot_table(index='state', columns='month', values='policy', aggfunc='count')

In [87]:
policies_by_month

month          1     2
state
Arizona     1008   929
California  1918  1634
Nevada       551   442
Oregon      1565  1344
Washington   463   425

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

In [175]:
#To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.
policies_by_month

month          1     2
state
Arizona     1008   929
California  1918  1634
Nevada       551   442
Oregon      1565  1344
Washington   463   425

In [172]:
#Next, you will select the top 3 states with the highest number of policies sold.
policies_by_month.sum(axis=1).sort_values(ascending=False).head(3).index

Index(['California', 'Oregon', 'Arizona'], dtype='str', name='state')

In [174]:
#Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.
result = policies_by_month.loc[policies_by_month.sum(axis=1).sort_values(ascending=False).head(3).index]
result

month          1     2
state
California  1918  1634
Oregon      1565  1344
Arizona     1008   929

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [215]:
ff = df.pivot_table(index='sales_channel', values='customer', aggfunc='count').round(2)
ff

               customer
sales_channel
Agent              4121
Branch             3022
Call Center        2141
Web                1626

In [216]:
ff1 = response_yes.pivot_table(index='sales_channel', values='customer', aggfunc='count').round(2)
ff1

               customer
sales_channel
Agent               742
Branch              326
Call Center         221
Web                 177

In [218]:
ff2 = ff1.div(ff).round(2)
ff2

               customer
sales_channel
Agent              0.18
Branch             0.11
Call Center        0.10
Web                0.11